#!/usr/bin/env python3
"""MAW-KG diagnostic report — the user-initiated submit layer.

Privacy contract:
- `report.md` generation is LOCAL and offline. The user reviews every line.
- Submission is EXPLICIT and offers two channels:
    --issue   file a GitHub issue (via `gh` CLI if authenticated, else
              prints a prefilled issue URL). GitHub notifies the maintainer
              by email automatically — that is the maintainer's inbox path.
    --send    POST the report to a maintainer endpoint (opt-in; the URL is
              taken from env MAW_KG_REPORT_ENDPOINT or repos.yaml key
              report_endpoint — both machine-local, never shipped).
- Nothing is ever transmitted without one of these explicit flags.

Usage:
    python src/report.py                # write work/report.md (local only)
    python src/report.py --issue        # + file/prefill a GitHub issue
    python src/report.py --send         # + POST to configured endpoint
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from error_log import read_entries  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
REPORT = ROOT / "work" / "report.md"
REPO_URL = "https://github.com/ZzXy47/maw-kg"
ENDPOINT_ENV = "MAW_KG_REPORT_ENDPOINT"


def _endpoint() -> str:
    v = os.environ.get(ENDPOINT_ENV, "").strip()
    if v:
        return v
    try:
        import yaml
        data = yaml.safe_load((ROOT / "repos.yaml").read_text(encoding="utf-8")) or {}
        return str(data.get("report_endpoint", "")).strip()
    except Exception:
        return ""


def _env_info() -> list[str]:
    import platform
    lines = [
        f"- python: {platform.python_version()} ({sys.maxsize > 2**32 and '64-bit' or '32-bit'})",
        f"- os: {platform.system()} {platform.release()}",
    ]
    for tool, probe in (("node", ["node", "--version"]),
                        ("git", ["git", "--version"]),
                        ("codegraph", ["codegraph", "--version"])):
        try:
            r = subprocess.run(probe, capture_output=True, text=True, timeout=10)
            lines.append(f"- {tool}: {(r.stdout or r.stderr).strip()[:60] or '?'}")
        except Exception:
            lines.append(f"- {tool}: (not found / probe failed)")
    return lines


def build_report(limit: int = 50) -> str:
    """Render the local diagnostic report. Environment + registered repos +
    indexed-repo health + captured error entries. No secrets, no user code."""
    from kg_config import REPO_ROOTS, NODE_EXE, CG_SHIM, GIT_EXE

    head = ["# MAW-KG diagnostic report",
            "",
            f"Generated locally by `python src/report.py`. Please review, redact "
            f"anything you do not want to share, then submit.",
            ""]

    head += ["## Environment", ""] + _env_info() + [
        f"- node exe: `{NODE_EXE}`",
        f"- cg shim: `{CG_SHIM or '(unresolved!)'}`",
        f"- git exe: `{GIT_EXE}`",
        "",
        "## Registered repos", ""]
    if REPO_ROOTS:
        for name, path in sorted(REPO_ROOTS.items()):
            db = Path(path) / ".codegraph" / "codegraph.db"
            if db.exists():
                size = db.stat().st_size
                health = "suspect-empty (<1MB)" if size < 1_048_576 else f"{size/1024/1024:.1f} MB"
                head.append(f"- {name}: index {health}")
            else:
                head.append(f"- {name}: **index missing**")
    else:
        head.append("- (no repos registered — repos.yaml not found or empty)")

    entries = read_entries(limit)
    head += ["", f"## Recent errors (newest first, last {len(entries)})", ""]
    if entries:
        for e in entries:
            head.append(f"- `{e.get('ts')} `{e.get('tool')}` — {e.get('error')}"
                         + (f" · args `{e.get('arg_shapes')}`" if e.get("arg_shapes") else ""))
    else:
        head.append("- (no errors captured — work/errors.jsonl empty or missing)")

    head += ["", "## Steps to reproduce (fill in)", "",
             "1. ", "2. ", "",
             "---", "",
             f"_report generated by MAW-KG · {REPO_URL}_", ""]
    return "\n".join(head)


def cmd_issue(text: str) -> int:
    """File a GitHub issue via gh if authenticated; else print prefilled URL."""
    try:
        r = subprocess.run(["gh", "auth", "status"], capture_output=True, text=True, timeout=15)
        gh_ok = r.returncode == 0
    except FileNotFoundError:
        gh_ok = False
    title = "Automated diagnostic report (please review before submitting)"
    if gh_ok:
        r = subprocess.run(
            ["gh", "issue", "create", "--repo", "ZzXy47/maw-kg",
             "--title", title, "--body-file", "-"],
            input=text, capture_output=True, text=True, timeout=60)
        if r.returncode == 0:
            print("Issue filed:", (r.stdout or "").strip())
            return 0
        print("gh issue create failed:", (r.stderr or r.stdout).strip(), file=sys.stderr)
    import urllib.parse
    url = (f"{REPO_URL}/issues/new?title=" + urllib.parse.quote(title)
           + "&body=" + urllib.parse.quote(text[:6000]))
    print("gh not authenticated — open this prefilled issue URL instead:\n" + url)
    return 0


def cmd_send(text: str) -> int:
    ep = _endpoint()
    if not ep:
        print(f"No endpoint configured. Set {ENDPOINT_ENV} or repos.yaml `report_endpoint:`.",
              file=sys.stderr)
        return 2
    req = urllib.request.Request(
        ep, data=json.dumps({"report": text}).encode("utf-8"),
        headers={"Content-Type": "application/json"}, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            print("Report sent:", resp.status)
            return 0
    except Exception as e:
        print(f"Report send failed: {e}", file=sys.stderr)
        return 1


def main() -> int:
    ap = argparse.ArgumentParser(description="MAW-KG diagnostic report (local + opt-in submit)")
    ap.add_argument("--limit", type=int, default=50, help="max error entries to include")
    ap.add_argument("--issue", action="store_true",
                    help="file a GitHub issue with the report (explicit user action)")
    ap.add_argument("--send", action="store_true",
                    help="POST the report to the configured endpoint (explicit user action)")
    a = ap.parse_args()

    text = build_report(a.limit)
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(text, encoding="utf-8")
    print(f"Report written to {REPORT} ({len(text)} chars). Review it first.")
    if a.issue:
        return cmd_issue(text)
    if a.send:
        return cmd_send(text)
    print("Submit with --issue (GitHub, notifies maintainer by email) or --send (endpoint).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
